export type Tutor = {
  id: string;
  name: string;
  faculty: string;
  major: string;
  year: string;
  courses: string[];
  pricePerSession: number;
  rating: number | null;
  reviewCount: number;
  photoUrl: string | null;
  joinedAt: string;
  bio: string;
  phone: string;
  status: "pending" | "approved";
  paymentStatus: "paid" | "unpaid";
};

export const mockTutors: Tutor[] = [
  {
    id: "1",
    name: "Rana Khalil",
    faculty: "Faculty of Engineering",
    major: "Computer Engineering",
    year: "Senior",
    courses: ["CSC 210", "MATH 201", "CSC 330"],
    pricePerSession: 15,
    rating: 4.8,
    reviewCount: 12,
    photoUrl: null,
    joinedAt: "2026-01-15",
    bio: "Senior Computer Engineering student passionate about breaking down tricky data structures and algorithms concepts. I've tutored classmates informally for two years and love a good whiteboard session.",
    phone: "96170111111",
    status: "approved",
    paymentStatus: "paid",
  },
  {
    id: "2",
    name: "Joe Baaklini",
    faculty: "Faculty of Business Administration",
    major: "Finance",
    year: "Senior",
    courses: ["ACC 201", "FIN 210"],
    pricePerSession: 10,
    rating: 4.5,
    reviewCount: 6,
    photoUrl: null,
    joinedAt: "2026-02-20",
    bio: "Finance major who's already passed both intro accounting and finance courses with top grades. I focus on making sure the fundamentals actually click before moving to harder problems.",
    phone: "96170222222",
    status: "approved",
    paymentStatus: "unpaid",
  },
  {
    id: "3",
    name: "Lea Matta",
    faculty: "Faculty of Engineering",
    major: "Mechanical Engineering",
    year: "Senior",
    courses: ["PHY 205", "MATH 202"],
    pricePerSession: 12,
    rating: null,
    reviewCount: 0,
    photoUrl: null,
    joinedAt: "2026-03-10",
    bio: "Mechanical engineering student who enjoys physics and calculus. New to tutoring but very patient and thorough — happy to go at your pace.",
    phone: "96170333333",
    status: "approved",
    paymentStatus: "paid",
  },
  {
    id: "4",
    name: "Nour Fares",
    faculty: "Faculty of Architecture, Art and Design",
    major: "Architecture",
    year: "Senior",
    courses: ["ARC 301"],
    pricePerSession: 18,
    rating: 5.0,
    reviewCount: 3,
    photoUrl: null,
    joinedAt: "2026-04-01",
    bio: "Architecture senior specializing in studio critique and design theory. I can help with both technical drafting questions and conceptual design thinking.",
    phone: "96170444444",
    status: "approved",
    paymentStatus: "paid",
  },
  {
    id: "5",
    name: "Karim Saad",
    faculty: "Faculty of Engineering",
    major: "Computer Engineering",
    year: "Senior",
    courses: ["CSC 220", "CSC 310"],
    pricePerSession: 14,
    rating: 4.6,
    reviewCount: 9,
    photoUrl: null,
    joinedAt: "2026-01-25",
    bio: "I passed both CSC 220 and CSC 310 with distinction and enjoy explaining object-oriented design and systems concepts in plain language.",
    phone: "96170555555",
    status: "approved",
    paymentStatus: "unpaid",
  },
  {
    id: "6",
    name: "Maya Chidiac",
    faculty: "Faculty of Engineering",
    major: "Computer Engineering",
    year: "Senior",
    courses: ["MATH 201", "CSC 210"],
    pricePerSession: 13,
    rating: 4.9,
    reviewCount: 15,
    photoUrl: null,
    joinedAt: "2026-02-05",
    bio: "Math-heavy courses are my specialty. I like building intuition first with simple examples before diving into formal proofs.",
    phone: "96170666666",
    status: "approved",
    paymentStatus: "paid",
  },
  {
    id: "7",
    name: "Elie Nasr",
    faculty: "Faculty of Engineering",
    major: "Computer Engineering",
    year: "Senior",
    courses: ["CSC 330", "CSC 401"],
    pricePerSession: 16,
    rating: 4.2,
    reviewCount: 4,
    photoUrl: null,
    joinedAt: "2026-02-28",
    bio: "Focused on advanced coursework like algorithms and systems design. I like problem-solving sessions over long lectures.",
    phone: "96170777777",
    status: "approved",
    paymentStatus: "paid",
  },
  {
    id: "8",
    name: "Sarah Abou Jaoude",
    faculty: "Faculty of Engineering",
    major: "Computer Engineering",
    year: "Senior",
    courses: ["MATH 202", "CSC 220"],
    pricePerSession: 11,
    rating: 4.7,
    reviewCount: 8,
    photoUrl: null,
    joinedAt: "2026-03-15",
    bio: "I've tutored a handful of classmates already and love turning confusing lecture material into something that actually makes sense.",
    phone: "96170888888",
    status: "pending",
    paymentStatus: "unpaid",
  },
  {
    id: "9",
    name: "Tarek Haddad",
    faculty: "Faculty of Engineering",
    major: "Computer Engineering",
    year: "Senior",
    courses: ["CSC 210", "CSC 401", "MATH 201"],
    pricePerSession: 17,
    rating: null,
    reviewCount: 0,
    photoUrl: null,
    joinedAt: "2026-04-10",
    bio: "New to tutoring on the platform but have helped friends prep for CSC exams for years. Flexible scheduling, in-person or online.",
    phone: "96170999999",
    status: "pending",
    paymentStatus: "unpaid",
  },
];
